version: '3.8'

services:
  graph_reader_api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./resources/kg:/app/resources/kg
    environment:
      - PYTHONUNBUFFERED=1
